version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: RelationalDatabase@2024!
      MYSQL_DATABASE: relational_database
      MYSQL_USER: mysql_default
      MYSQL_PASSWORD: RelationalDatabase@2024!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: